---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aad-pod-identity
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./lib/aad-pod-identity
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
