---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: managed-ids
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./clusters/stealthybox/azure-identities
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  dependsOn:
    - name: aad-pod-identity
